
- hosts: webservers
  vars:
    java_download: http://download.oracle.com/otn-pub/java/jdk/8u112-b15/jdk-8u112-linux-x64.tar.gz
    java_name: "jdk1.8.0_112"
    download_folder: "/usr/bin"
    java_archive: "{{download_folder}}/jdk-8u112-linux-x64.tar.gz"
    java_folder: /usr/lib/jvm
    java_alias: java-8-oracle
    java_controller: "/root/balu/ansi_playbooks/jdk-8u112-linux-x64.tar.gz"

  tasks:

  - name: Install tar
    yum: pkg=tar

  - name: Install wget
    yum: pkg=wget

  - name: Install unzip
    yum: pkg=unzip
  - file:
      path: "{{download_folder}}"
      owner: root
      mode: 0755
  - name: Download java
    get_url: 'url={{java_download}} dest={{download_folder}} headers="Cookie:gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" checksum=md5:de9b7a90f0f5a13cfcaa3b01451d0337'

  - name: Download and unpack
    unarchive:
      src: "{{download_folder}}/jdk-8u112-linux-x64.tar.gz"
      dest: "{{download_folder}}"
      copy: no
      owner: root
      mode: 0755
      list_files: true
      creates: "{{java_name}}"

  - name: Fix ownership
    file: "state=directory path={{download_folder}}/{{java_name}}  owner=root recurse=yes"

  - name: Create Java folder
    file: "state=directory path={{java_folder}}"

  - name: Move Java to final folder
    command: "mv {{download_folder}}/{{java_name}} {{java_folder}} creates={{java_folder}}/{{java_name}}"

  - name: Create symlink for easier update
    file: "state=link src={{java_folder}}/{{java_name}} dest={{java_folder}}/{{java_alias}}"

  - name: Make Java available for system
    command: 'update-alternatives --install "/usr/bin/java" "java" "{{download_folder}}/{{java_name}}/bin/java" 2'

  - name: Make the Javac available for systems
    command: 'update-alternatives --install "/usr/bin/javac" "javac" "{{download_folder}}/{{java_name}}/bin/javac" 1'

  - name: Make the jar available for systems
    command: 'update-alternatives --install "/usr/bin/jar" "jar" "{{download_folder}}/{{java_name}}/bin/jar" 1'

  - name: Echo Java_Home variables
    action: lineinfile dest=/etc/profile line='export  JAVA_HOME=$JAVA_HOME:{{download_folder}}/{{java_name}}' insertafter='EOF' regexp='export JAVA_HOME.*'  state=present

  - name: Echo Jre_Home variables
    action: lineinfile dest=/etc/profile line='export  JRE_HOME={{download_folder}}/{{java_name}}/jre' insertafter='EOF' regexp='export JRE_HOME.*'  state=present


  - name: save the java_home into etc profile
    shell: source /etc/profile


  - shell: echo JAVA_HOME is $JAVA_HOME
    environment:
      JAVA_HOME: $JAVA_HOME:{{download_folder}}{{java_name}}
      JRE_HOME: JRE_HOME:{{download_folder}}/{{java_name}}/jre
      PATH: $PATH:$JAVA_HOME/bin
    register: shellout
  - debug: var=shellout


  - name: echo PATH
    action: lineinfile dest=/etc/profile line='export PATH=$PATH:{{download_folder}}/{{java_name}}/bin:{{download_folder}}/{{java_name}}/jre' insertafter='EOF' regexp='export PATH.*'  state=present

  - name: save the path into etc profile
    shell: source /etc/profile

#set the bash profile as ./bash_profile

  - name: Echo Java_Home variables
    action: lineinfile dest=~/.bash_profile line='export  JAVA_HOME=$JAVA_HOME:{{download_folder}}/{{java_name}}' insertafter='EOF' regexp='export JAVA_HOME.*'  state=present

  - name: Echo Jre_Home variables
    action: lineinfile dest=~/.bash_profile line='export  JRE_HOME={{download_folder}}/{{java_name}}/jre' insertafter='EOF' regexp='export JRE_HOME.*'  state=present

  - name: save the java_home into etc profile
    shell: source ~/.bash_profile


  - shell: echo JAVA_HOME is $JAVA_HOME
    environment:
      JAVA_HOME: $JAVA_HOME:{{download_folder}}{{java_name}}
      JRE_HOME: $JRE_HOME:{{download_folder}}/{{java_name}}/jre
      PATH: $PATH:$JAVA_HOME/bin
    register: shellout
  - debug: var=shellout


  - name: echo PATH
    action: lineinfile dest=~/.bash_profile line='export PATH=$PATH:{{download_folder}}/{{java_name}}/bin:{{download_folder}}/{{java_name}}/jre' insertafter='EOF' regexp='export PATH.*'  state=present

  - name: save the path into etc profile
    shell: source ~/.bash_profile

#set the bashrc in ~/.bashrc

  - name: Echo Java_Home variables
    action: lineinfile dest=~/.bashrc line='export  JAVA_HOME=$JAVA_HOME:{{download_folder}}/{{java_name}}' insertafter='EOF' regexp='export JAVA_HOME.*'  state=present

  - name: Echo Jre_Home variables
    action: lineinfile dest=~/.bashrc line='export  JRE_HOME={{download_folder}}/{{java_name}}/jre' insertafter='EOF' regexp='export JRE_HOME.*'  state=present

  - name: save the java_home into etc profile
    shell: source ~/.bashrc


  - shell: echo JAVA_HOME is $JAVA_HOME
    environment:
      JAVA_HOME: $JAVA_HOME:{{download_folder}}{{java_name}}
      JRE_HOME: $JRE_HOME:{{download_folder}}/{{java_name}}/jre
      PATH: $PATH:$JAVA_HOME/bin
    register: shellout
  - debug: var=shellout


  - name: echo PATH
    action: lineinfile dest=~/.bashrc line='export PATH=$PATH:{{download_folder}}/{{java_name}}/bin:{{download_folder}}/{{java_name}}/jre' insertafter='EOF' regexp='export PATH.*'  state=present

  - name: save the path into etc profile
    shell: source ~/.bashrc






